apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: traffic-refresher
build:
  artifacts:
  - image: gcr.io/aurora-alarm/traffic-refresher
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deploy.yaml
