//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.15 at 01:40:07 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datex2.eu/schema/2/2_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.datex2.schema._2._2_0;
